export const stewartChapters = [
  {
    id: "functions-models",
    title: "Functions and Models",
    description: "Introduction to functions, mathematical models, and graphing techniques",
    order: 1,
    topics: [
      "four-ways-represent-function",
      "mathematical-models",
      "new-functions-old",
      "exponential-functions",
      "inverse-functions-logarithms",
    ],
  },
  {
    id: "limits-derivatives",
    title: "Limits and Derivatives",
    description: "The foundation of calculus: limits, continuity, and introduction to derivatives",
    order: 2,
    topics: [
      "tangent-velocity-problems",
      "limit-function",
      "calculating-limits",
      "continuity",
      "limits-infinity",
      "derivatives-rates-change",
      "derivative-function",
    ],
  },
  {
    id: "differentiation-rules",
    title: "Differentiation Rules",
    description: "Rules and techniques for finding derivatives of various functions",
    order: 3,
    topics: [
      "derivatives-polynomials",
      "product-quotient-rules",
      "derivatives-trigonometric",
      "chain-rule",
      "implicit-differentiation",
      "derivatives-logarithmic",
      "rates-change-sciences",
      "exponential-growth-decay",
      "related-rates",
      "linear-approximations",
    ],
  },
  {
    id: "applications-differentiation",
    title: "Applications of Differentiation",
    description: "Using derivatives to solve optimization and graphing problems",
    order: 4,
    topics: [
      "maximum-minimum-values",
      "mean-value-theorem",
      "derivatives-shape-graph",
      "indeterminate-forms",
      "summary-curve-sketching",
      "graphing-calculators",
      "optimization-problems",
      "newtons-method",
      "antiderivatives",
    ],
  },
  {
    id: "integrals",
    title: "Integrals",
    description: "Introduction to integration and the Fundamental Theorem of Calculus",
    order: 5,
    topics: [
      "areas-distances",
      "definite-integral",
      "fundamental-theorem",
      "indefinite-integrals",
      "substitution-rule",
    ],
  },
  {
    id: "applications-integration",
    title: "Applications of Integration",
    description: "Using integrals to find areas, volumes, and solve real-world problems",
    order: 6,
    topics: ["areas-between-curves", "volumes", "volumes-cylindrical-shells", "work", "average-value-function"],
  },
]

export const stewartTopics = [
  // Chapter 1: Functions and Models
  {
    id: "four-ways-represent-function",
    chapterId: "functions-models",
    title: "Four Ways to Represent a Function",
    description: "Verbal, numerical, visual, and algebraic representations",
    order: 1,
  },
  {
    id: "mathematical-models",
    chapterId: "functions-models",
    title: "Mathematical Models: A Catalog of Essential Functions",
    description: "Linear, polynomial, power, rational, algebraic, and transcendental functions",
    order: 2,
  },
  {
    id: "new-functions-old",
    chapterId: "functions-models",
    title: "New Functions from Old Functions",
    description: "Transformations, combinations, and compositions of functions",
    order: 3,
  },
  {
    id: "exponential-functions",
    chapterId: "functions-models",
    title: "Exponential Functions",
    description: "Properties and graphs of exponential functions",
    order: 4,
  },
  {
    id: "inverse-functions-logarithms",
    chapterId: "functions-models",
    title: "Inverse Functions and Logarithms",
    description: "Finding and working with inverse functions and logarithmic functions",
    order: 5,
  },

  // Chapter 2: Limits and Derivatives
  {
    id: "tangent-velocity-problems",
    chapterId: "limits-derivatives",
    title: "The Tangent and Velocity Problems",
    description: "Introduction to the fundamental problems that lead to derivatives",
    order: 1,
  },
  {
    id: "limit-function",
    chapterId: "limits-derivatives",
    title: "The Limit of a Function",
    description: "Understanding limits graphically and numerically",
    order: 2,
  },
  {
    id: "calculating-limits",
    chapterId: "limits-derivatives",
    title: "Calculating Limits Using the Limit Laws",
    description: "Algebraic techniques for evaluating limits",
    order: 3,
  },
  {
    id: "continuity",
    chapterId: "limits-derivatives",
    title: "Continuity",
    description: "Definition and properties of continuous functions",
    order: 4,
  },
  {
    id: "limits-infinity",
    chapterId: "limits-derivatives",
    title: "Limits at Infinity; Horizontal Asymptotes",
    description: "Behavior of functions as x approaches infinity",
    order: 5,
  },
  {
    id: "derivatives-rates-change",
    chapterId: "limits-derivatives",
    title: "Derivatives and Rates of Change",
    description: "The derivative as a rate of change and slope of tangent line",
    order: 6,
  },
  {
    id: "derivative-function",
    chapterId: "limits-derivatives",
    title: "The Derivative as a Function",
    description: "Understanding the derivative function and its properties",
    order: 7,
  },

  // Chapter 3: Differentiation Rules
  {
    id: "derivatives-polynomials",
    chapterId: "differentiation-rules",
    title: "Derivatives of Polynomials and Exponential Functions",
    description: "Power rule and derivatives of exponential functions",
    order: 1,
  },
  {
    id: "product-quotient-rules",
    chapterId: "differentiation-rules",
    title: "The Product and Quotient Rules",
    description: "Rules for differentiating products and quotients of functions",
    order: 2,
  },
  {
    id: "derivatives-trigonometric",
    chapterId: "differentiation-rules",
    title: "Derivatives of Trigonometric Functions",
    description: "Finding derivatives of sine, cosine, and other trig functions",
    order: 3,
  },
  {
    id: "chain-rule",
    chapterId: "differentiation-rules",
    title: "The Chain Rule",
    description: "Differentiating composite functions",
    order: 4,
  },
  {
    id: "implicit-differentiation",
    chapterId: "differentiation-rules",
    title: "Implicit Differentiation",
    description: "Finding derivatives when y is not explicitly solved for",
    order: 5,
  },
  {
    id: "derivatives-logarithmic",
    chapterId: "differentiation-rules",
    title: "Derivatives of Logarithmic Functions",
    description: "Differentiation involving natural and common logarithms",
    order: 6,
  },
  {
    id: "rates-change-sciences",
    chapterId: "differentiation-rules",
    title: "Rates of Change in the Natural and Social Sciences",
    description: "Applications of derivatives in various fields",
    order: 7,
  },
  {
    id: "exponential-growth-decay",
    chapterId: "differentiation-rules",
    title: "Exponential Growth and Decay",
    description: "Mathematical models involving exponential functions",
    order: 8,
  },
  {
    id: "related-rates",
    chapterId: "differentiation-rules",
    title: "Related Rates",
    description: "Problems involving rates of change of related quantities",
    order: 9,
  },
  {
    id: "linear-approximations",
    chapterId: "differentiation-rules",
    title: "Linear Approximations and Differentials",
    description: "Using derivatives to approximate function values",
    order: 10,
  },
  // Add all topics for Chapter 4: Applications of Differentiation
  {
    id: "maximum-minimum-values",
    chapterId: "applications-differentiation",
    title: "Maximum and Minimum Values",
    description: "Finding absolute and local extrema of functions",
    order: 1,
  },
  {
    id: "mean-value-theorem",
    chapterId: "applications-differentiation",
    title: "The Mean Value Theorem",
    description: "Understanding and applying the Mean Value Theorem",
    order: 2,
  },
  {
    id: "derivatives-shape-graph",
    chapterId: "applications-differentiation",
    title: "How Derivatives Affect the Shape of a Graph",
    description: "Using first and second derivatives to analyze graphs",
    order: 3,
  },
  {
    id: "indeterminate-forms",
    chapterId: "applications-differentiation",
    title: "Indeterminate Forms and L'Hôpital's Rule",
    description: "Evaluating limits of indeterminate forms",
    order: 4,
  },
  {
    id: "summary-curve-sketching",
    chapterId: "applications-differentiation",
    title: "Summary of Curve Sketching",
    description: "Comprehensive approach to graphing functions",
    order: 5,
  },
  {
    id: "graphing-calculators",
    chapterId: "applications-differentiation",
    title: "Graphing with Calculators and Computers",
    description: "Using technology to analyze and graph functions",
    order: 6,
  },
  {
    id: "optimization-problems",
    chapterId: "applications-differentiation",
    title: "Optimization Problems",
    description: "Solving real-world optimization problems using calculus",
    order: 7,
  },
  {
    id: "newtons-method",
    chapterId: "applications-differentiation",
    title: "Newton's Method",
    description: "Numerical method for finding roots of equations",
    order: 8,
  },
  {
    id: "antiderivatives",
    chapterId: "applications-differentiation",
    title: "Antiderivatives",
    description: "Introduction to antiderivatives and indefinite integrals",
    order: 9,
  },

  // Add all topics for Chapter 5: Integrals
  {
    id: "areas-distances",
    chapterId: "integrals",
    title: "Areas and Distances",
    description: "Introduction to integration through area and distance problems",
    order: 1,
  },
  {
    id: "definite-integral",
    chapterId: "integrals",
    title: "The Definite Integral",
    description: "Definition and properties of definite integrals",
    order: 2,
  },
  {
    id: "fundamental-theorem",
    chapterId: "integrals",
    title: "The Fundamental Theorem of Calculus",
    description: "Connecting derivatives and integrals",
    order: 3,
  },
  {
    id: "indefinite-integrals",
    chapterId: "integrals",
    title: "Indefinite Integrals and the Net Change Theorem",
    description: "Antiderivatives and applications to net change",
    order: 4,
  },
  {
    id: "substitution-rule",
    chapterId: "integrals",
    title: "The Substitution Rule",
    description: "Technique for evaluating integrals using substitution",
    order: 5,
  },

  // Add all topics for Chapter 6: Applications of Integration
  {
    id: "areas-between-curves",
    chapterId: "applications-integration",
    title: "Areas Between Curves",
    description: "Finding areas between two or more curves",
    order: 1,
  },
  {
    id: "volumes",
    chapterId: "applications-integration",
    title: "Volumes",
    description: "Computing volumes using cross-sections and disk/washer methods",
    order: 2,
  },
  {
    id: "volumes-cylindrical-shells",
    chapterId: "applications-integration",
    title: "Volumes by Cylindrical Shells",
    description: "Shell method for finding volumes of revolution",
    order: 3,
  },
  {
    id: "work",
    chapterId: "applications-integration",
    title: "Work",
    description: "Applications of integration to work problems",
    order: 4,
  },
  {
    id: "average-value-function",
    chapterId: "applications-integration",
    title: "Average Value of a Function",
    description: "Finding average values using integration",
    order: 5,
  },
]
